### ISSUE TITLE
[beta] CursorOptions do not resolve correctly

### ISSUE THREAD

**Issue by Brodzko** [TanStack/react-charts#233]
Concerns both `primaryCursor` and `secondaryCursor` options of `ChartOptions`.

When passing a boolean value or even `{ show: false }` to these options, they don't work as one would expect since `showLabel` and `showLine` take precedence and default to `true`. See [here](https://github.com/tannerlinsley/react-charts/blob/c8a5867d7f5bbacf696c703e1c0f0ef518359da5/src/components/Cursors.tsx#L31).

**Comment by tannerlinsley** [comment]
Good catch. I'll get these fixed.
