### ISSUE TITLE
Hovering on Chart Throws Error

### ISSUE THREAD

**Issue by chidera-ugo** [TanStack/react-charts#300]
I think this occurs only in development

If you hover on any of the charts in the [codesandbox examples](https://codesandbox.io/s/github/tannerlinsley/react-charts/tree/beta/examples/simple?from-embed) you'll get this type error

`Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.`

<img width="1440" alt="Screenshot 2022-08-04 at 11 27 18" src="https://user-images.githubusercontent.com/69648843/182825611-1db35b7d-e5c3-4a55-bef1-a201ae494ea0.png">

Same thing on Safari and Chrome. But it seems to work fine in prod

**Comment by adxl** [comment]
Same thing with the [Getting Started example](https://react-charts.tanstack.com/docs/getting-started) in the documentation

**Comment by chidera-ugo** [comment]
exactly

**Comment by chidera-ugo** [comment]
Closing this because it seems to have been resolved
