### ISSUE TITLE
How to add fill color in line chart?

### ISSUE THREAD

**Issue by ibrahimrehman1** [TanStack/react-charts#311]
I am creating a line chart using react-charts but unable to set the fill color i.e. the color of the region below the line. This is the current state of my chart. Any help would be appreciated. Thanks :)

![Screenshot from 2022-09-16 21-54-37](https://user-images.githubusercontent.com/63722045/190690942-7d7c8d1e-cd94-4db4-9479-2312ee42bc17.png)

**Comment by tannerlinsley** [comment]
You'll want to use the area series type instead of a line

**Comment by ibrahimrehman1** [comment]
Alright thanks for letting me know :)
