### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by horlakz** [TanStack/react-charts#314]
I'm having issues fixing this in nextjs, please who can suggest a solution for me or better still another easier chart library

**Comment by chimp1nski** [comment]
Hey @Horlakz you can find a fix for this issue in #304 provided by @joshuabaker
This works fine for me.

**Comment by horlakz** [comment]
alright thank you @chimp1nski , will close this issue now
