### ISSUE TITLE
Is this library maintained anymore?

### ISSUE THREAD

**Issue by rfdrake27** [TanStack/react-charts#318]
There are many unresolved issues in this library, some of which are critical problems that have existed for almost a year. 

There appear to be no fixes for major problems like #261 or #301.

Is there a new expected release date for fixes? Or should we migrate to a different library?

**Comment by elhe26** [comment]
Same question.

**Comment by tannerlinsley** [comment]
It’s definitely maintained. Just not at the priority it deserves. It’s next on my list after TanStack Router for upgrade.

**Comment by rfdrake27** [comment]
Thanks for dropping by with the update Tanner. I'm glad it's on your list. Thank you for all you have created for the community.
